openapi: 3.0.1
info:
  title: User Management API
  description: API simples para gerenciamento de usuários
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      summary: Retorna todos os usuários
      operationId: getUsers
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
    post:
      summary: Cria um novo usuário
      operationId: createUser
      requestBody:
        description: Dados do novo usuário
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
  /users/{id}:
    get:
      summary: Retorna um usuário pelo ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Usuário não encontrado
    put:
      summary: Atualiza os dados de um usuário
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser atualizado
          schema:
            type: integer
      requestBody:
        description: Dados atualizados do usuário
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Usuário não encontrado
    delete:
      summary: Deleta um usuário pelo ID
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser deletado
          schema:
            type: integer
      responses:
        '204':
          description: Usuário deletado com sucesso
        '404':
          description: Usuário não encontrado
